version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - postgres_db
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
      DB_HOST: 0.0.0.0
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: postgres
      DB_PROTOCOL: postgresql://
  postgres_db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: '1234'
