version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - postgresdb
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
      DB_HOST: 172.18.0.2
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: postgres
      PROTOCOL: postgresql://
    networks:
      school_network:
        ipv4_address: 172.18.0.3

  postgresdb:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: '1234'
    networks:
      school_network:
        ipv4_address: 172.18.0.2   # IP address of postgresdb service

networks:
  school_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
